application: appname
version: 0_0_1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1s
  max_pending_latency: 4s

handlers:
- url: /favicon\.ico
  static_files: static/vortext_logo.png
  upload: static/vortext_logo.png

- url: /static
  static_dir: static

- url: /auth/.*
  script: auth.app

- url: /tasks/.*
  script: tasks.app
  login: admin

- url: /admin.*
  script: main.app
  login: admin

- url: .*
  script: main.app

inbound_services:
- warmup

